### ISSUE TITLE
Uncaught TypeError: Cannot call method 'createDocumentFragment' of undefined 

### ISSUE THREAD

**Issue by infacq** [ftlabs/ftscroller#60]
```
    require(["ftscroller"], function() {
            var scroller = new FTScroller($content, {
                        scrollingX: false
            }); 
    });
```

not sure why it triggered the error..

**Comment by macs91** [comment]
@infacq what was the problem for you? I'm having the same issue

**Comment by macs91** [comment]
I solved it too, in my case it was related to the fact that I was passing to the `FTScroller` constructor an object that was not a DOM element (This because I'm using [styled components](https://www.styled-components.com/docs/advanced#refs), and I was using `ref` instead of `innerRef`)
