### ISSUE TITLE
syncing with another element

### ISSUE THREAD

**Issue by danschumann** [ftlabs/ftscroller#99]
Hello,

I can listen to the `scroll` event, but that doesn't fire often enough to keep another element up to date.

Application is for a table with a header row and first column that are locked in place, where the tables scrolls underneath, and the fixed parts stay updated.

What's the best way to exactly mimic the scroll behavior of an element?

**Comment by danschumann** [comment]
I should mention it works perfectly when dragging(not flinging), but the table could be 2000 rows, so I'd like fling to work too.

**Comment by danschumann** [comment]
I could try to grab the `style` attribute from either the x or y element and copy them to my synced element... if there isn't a better way?

**Comment by fengdh** [comment]
I have modified ftscroller.js to synchronize **_fling_** between another element perfectly by firing new **`fling`** event.

1. Add '**`fling`**' to supported event listeners:
```
FTScroller = function (domNode, options) {
..
	// Event listeners
	var _eventListeners = {
		'scrollstart': [],
		'scroll': [],
		'scrollend': [],
		'segmentwillchange': [],
		'segmentdidchange': [],
		'reachedstart': [],
		'reachedend': [],
		'scrollinteractionend': [],
		// Add support for fling event listener     <----------
		'fling': []
	};
```

2. Fire 'fling' event here:
```
_setAxisPosition = function _setAxisPosition(
..
	// Update the recorded position if there's no duration
	if (!animationDuration) {
		_lastScrollPosition[axis] = position;
	// Fire fling event when fling actually happened.   <---------
	} else {
		_fireEvent('fling', {axis: axis, flingDuration: animationDuration, flingPosition: position});
	}
}
```

3. Synchronize on ftscroller with another one:
```
srcFTScroller.addEventListener(function(obj) {
	var target = targetFTScroller.contentContainerNode;
	var src    = obj.srcObject.contentContainerNode;

	target.style.transition = src.style.transition;
	target.style.transform  = src.style.transform;
});
```

**Comment by danschumann** [comment]
+1
